config/routes.rb
Portal::Application.routes.draw do

  # Non-resource controllers
  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  # Resources
  resources :users
  resources :organizations do
    resources :employments do
      member do
        put 'add_head_contact'
        put 'remove_head_contact'
      end
    end
    
    resources :opening_hours, :only => :create
  end

  resources :opening_hours
  resources :campaigns

  # Slugs
  match 'profile' => 'users#profile'
  # Root
  root :to => 'dashboard#index'
  
  # API routes
  namespace :api do
    controller :login do
      get 'login' => :new
      post 'login' => :new
    end
    
    controller :organizations do
      get 'organizations' => :index
      get 'organizations/:id/campaigns' => :campaigns
      get 'organizations/:id/opening_hours' => :opening_hours
    end
  end

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  ROLES = {
    'Employee' => 'employee',
    'Manager' => 'manager'
  }

  belongs_to :user
  belongs_to :organization
  
  validates :role, :inclusion => %w(manager employee)
  validates :user_id, :uniqueness => { :scope => :organization_id }
  
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController

  before_filter :find_organization

  def create  
    @employment              = Employment.new
    @employment.user         = User.find_by_email(params[:email])
    @employment.organization = @organization
    @employment.role         = params[:role]
    @employment.save
  end
  
  def destroy
    @employment = Employment.find params[:id]
    @employment.destroy
  end
  
  def add_head_contact
    @employment = Employment.find params[:id]
    @employment.update_attribute :is_head_contact, true
  end
  
  def remove_head_contact
    @employment = Employment.find params[:id]
    @employment.update_attribute :is_head_contact, false
  end
  
  protected
  
    def find_organization
      @organization = Organization.find params[:organization_id]
    end

end

app/views/employments/_employment.html.haml
= content_tag_for :div, employment, :class => 'btn-group' do |employment|
  .btn-group
    = link_to employment.user, :class => 'btn btn-primary' do
      - if employment.role == 'manager'
        %i.icon-user.icon-white
      = employment.user.name
    %button.btn.btn-primary.dropdown-toggle{'data-toggle' => 'dropdown'}
      %span.caret
    %ul.dropdown-menu
      - if employment.is_head_contact?
        %li= link_to iconize('Remove as head contact', 'arrow-down'), remove_head_contact_organization_employment_path(@organization, employment), :method => :put, :remote => true
      - else
        %li= link_to iconize('Add as head contact', 'arrow-up'), add_head_contact_organization_employment_path(@organization, employment), :method => :put, :remote => true
      %li= link_to iconize('Remove', 'ban-circle'), organization_employment_path(@organization, employment), :method => :delete, :remote => true

app/views/employments/add_head_contact.js.erb
$('#head_contacts').html('<%= j render 'organizations/head_contacts' %>');
$('#user_<%= @employment.user.id %>').hide().slideDown();

app/views/employments/create.js.erb
$('#employments').html('<%= j render @organization.employments %>');
$('#employment_<%= @employment.id %>').hide().show('slow');

app/views/employments/destroy.js.erb
$('#employment_<%= @employment.id %>').hide('slow');
$('#user_<%= @employment.user.id %>').hide('slow');

app/views/employments/remove_head_contact.js.erb
$('#user_<%= @employment.user.id %>').slideUp();