config/routes.rb
Portal::Application.routes.draw do

  # Non-resource controllers
  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  # Resources
  resources :users
  resources :organizations do
    resources :employments do
      member do
        put 'add_head_contact'
        put 'remove_head_contact'
      end
    end
    
    resources :opening_hours, :only => :create
  end

  resources :opening_hours
  resources :campaigns

  # Slugs
  match 'profile' => 'users#profile'
  # Root
  root :to => 'dashboard#index'
  
  # API routes
  namespace :api do
    controller :login do
      get 'login' => :new
      post 'login' => :new
    end
    
    controller :organizations do
      get 'organizations' => :index
      get 'organizations/:id/campaigns' => :campaigns
      get 'organizations/:id/opening_hours' => :opening_hours
    end
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  attr_accessible :name, :address, :zipcode, :city, :telephone

  has_many :employments, :dependent => :destroy
  has_many :users, :through => :employments
  has_many :orders, :dependent => :nullify
  has_many :opening_hours, :dependent => :destroy
  has_many :standard_opening_hours, :class_name => 'StandardOpeningHour'
  has_many :special_opening_hours, :class_name => 'SpecialOpeningHour', :order => 'date'
  has_many :assortments, :dependent => :destroy
  has_many :products, :through => :assortments
  has_many :campaigns, :dependent => :destroy
  
  after_create :create_opening_hours
  
  has_ancestry

  def head_contacts
    users.where(:employments => {:is_head_contact => true})
  end
  
  def create_opening_hours!
    StandardOpeningHour::DAYS.keys.each do |day|
      opening_hour = StandardOpeningHour.new :from => '00:00', :to => '00:00', :day => day
      self.opening_hours << opening_hour
    end
  end

end

app/controllers/api/organizations_controller.rb
class Api::OrganizationsController < Api::ApiController

  def index
    @organizations = Organization.all
  
    respond_to do |format|
      format.json { render :json => @organizations }
      format.xml  { render :xml  => @organizations }
    end
  end
  
  def campaigns
    @organization = Organization.find params[:id]
    
    respond_to do |format|
      format.json { render :json => @organization.campaigns }
      format.xml  { render :xml  => @organization.campaigns }
    end
  end
  
  def opening_hours
    @organization = Organization.find params[:id]
    hours = {}
    
    ((Date.current.beginning_of_week)..(Date.current.end_of_week + 1.week)).each do |date|
      o = @organization.special_opening_hours.find_by_date(date)
      o ||= @organization.standard_opening_hours.find_by_day(date.wday)
      hours[date] = "#{l o.from, :format => '%H:%M'} - #{l o.to, :format => '%H:%M'}"
    end
    
    respond_to do |format|
      format.json { render :json => hours }
      format.xml  { render :xml  => hours }
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_filter :find_organization, :only => [:show, :edit, :update, :destroy]

  before_filter :require_superuser, :except => [:show]
  before_filter(:only => :show) { |c| c.require_staff(@organization) }

  def index
    @search = Organization.search(params[:search])
    @organizations = @search.paginate(:page => params[:page])
  end
  
  def show
    @special_opening_hour = SpecialOpeningHour.new
  end
  
  def edit
  end
  
  def new
    @organization = Organization.new
  end
  
  def create
    @organization = Organization.new params[:organization]

    if @organization.save
      redirect_to @organization, notice: 'Organization was succesfully created.'
    else
      render :new
    end
  end
  
  def update
    if @organization.update_attributes params[:organization]
      redirect_to @organization, notice: 'Organization was succesfully updated.'
    else
      render :edit
    end
  end
  
  protected
  
    def find_organization
      @organization = Organization.find params[:id]
    end
end

app/views/organizations/_details.html.haml
.row
  .span6
    %dl.dl-horizontal
      - if @organization.parent.present?
        %dt Subsidiary of
        %dd= link_to @organization.parent.name, @organization.parent
      %dt  Address
      %dd
        = @organization.address
        %br
        = @organization.zipcode
        = @organization.city
      %dt  Telephone
      %dd= @organization.telephone
      %dt  Head contacts
      %dd#head_contacts
        = render 'head_contacts'
  .span6
    %section
      %h2 Users
      #add_user_form
        = form_for [@organization, Employment.new], :remote => true, :html => {:class => 'form-inline'} do |f|
          = text_field_tag 'email', '', :placeholder => 'E-mail address', :class => 'input-medium'
          = select_tag 'role', options_for_select(Employment::ROLES), :class => 'input-medium'
          = f.submit 'Add'
      %p#employments
        = render @organization.employments
- if @organization.children.present?
  %h2 Subsidiaries
  %table.table.table-bordered
    %thead
      %tr
        %th Name
        %th Address
        %th Zipcode
        %th City
        %th Telephone
        %th
    %tbody
      - @organization.children.each do |organization|
        %tr
          %td= link_to organization.name, organization
          %td= organization.address
          %td= organization.zipcode
          %td= organization.city
          %td= organization.telephone
          %td

app/views/organizations/_form.html.haml
= simple_form_for @organization, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :address
  = f.input :zipcode
  = f.input :city
  = f.input :telephone
  = f.input :lat
  = f.input :long
  
  .form-actions
    = f.submit

app/views/organizations/_head_contacts.html.haml
%ul
  = content_tag_for :li, @organization.head_contacts do |head_contact|
    #{head_contact.name} (#{head_contact.telephone})

app/views/organizations/_new_opening_hour.html.haml
= simple_form_for [@organization, @special_opening_hour], :html => { :class => 'form-horizontal' }, :remote => true do |f|
  = f.input :date, :input_html => { :class => 'input-small' }
  = f.input :from, :input_html => { :class => 'input-mini' }
  = f.input :to,   :input_html => { :class => 'input-mini' }
  .form-actions= f.submit

app/views/organizations/_opening_hours.html.haml
.row
  .span6
    %h2 Standard opening hours
    %table.table.table-bordered
      %thead
        %tr
          %th Day
          %th Hours
      %tbody
        = render :partial => 'opening_hours/opening_hour', :collection => @organization.standard_opening_hours
  .span6
    %h2 Special opening hours
    %table.table.table-bordered
      %thead
        %tr
          %th Date
          %th Hours
      %tbody#special_opening_hours
        = render :partial => 'opening_hours/opening_hour', :collection => @organization.special_opening_hours
    %h4 New record
    = render 'new_opening_hour'

app/views/organizations/edit.html.haml
.page-header
  %h1 Edit organization

= render 'form'

app/views/organizations/index.html.haml
.page-header
  %h1
    Organizations
    .pull-right
      = link_to 'New organization', new_organization_path, :class => 'btn'
%table.table.table-striped
  %thead
    %tr
      %th= sort_link @search, :id, '#'
      %th= sort_link @search, :name
      %th
  %tbody
    - @organizations.each do |organization|
      %tr
        %td= organization.id
        %td= organization.name
        %td
          = link_to organization, :class => 'btn btn-small' do
            %i.icon-eye-open
            Show
          = link_to edit_organization_path(organization), :class => 'btn btn-small' do
            %i.icon-pencil
            Edit
          = link_to organization_path(organization), :confirmation => 'Are you sure you cant to delete this organization?', :remote => true, :method => :delete, :class => 'btn btn-danger btn-small' do
            %i.icon-trash.icon-white
            Delete
= will_paginate @organizations

app/views/organizations/new.html.haml
.page-header
  %h1 Create organization

= render 'form'

app/views/organizations/show.html.haml
%h1
  = @organization.name
%ul.nav.nav-tabs
  %li.active= link_to 'Details', '#details', 'data-toggle' => 'tab'
  %li= link_to 'Orders'
  %li= link_to 'Statistics'
  %li= link_to 'Opening hours', '#opening_hours', 'data-toggle' => 'tab'
.tab-content
  #details.tab-pane.active
    = render 'details'
  #opening_hours.tab-pane
    = render 'opening_hours'