config/routes.rb
Portal::Application.routes.draw do

  # Non-resource controllers
  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  # Resources
  resources :users
  resources :organizations do
    resources :employments do
      member do
        put 'add_head_contact'
        put 'remove_head_contact'
      end
    end
    
    resources :opening_hours, :only => :create
  end

  resources :opening_hours
  resources :campaigns

  # Slugs
  match 'profile' => 'users#profile'
  # Root
  root :to => 'dashboard#index'
  
  # API routes
  namespace :api do
    controller :login do
      get 'login' => :new
      post 'login' => :new
    end
    
    controller :organizations do
      get 'organizations' => :index
      get 'organizations/:id/campaigns' => :campaigns
      get 'organizations/:id/opening_hours' => :opening_hours
    end
  end

end

app/helpers/layout_helper.rb
module LayoutHelper
  def iconize(body, icon)
    (content_tag(:i, nil, :class => "icon-#{icon}") + ' ' + body).html_safe
  end
end

app/views/layouts/application.html.haml
!!!
%html{'lang' => 'en'}
  %head
    = stylesheet_link_tag :application, media: 'all'
    = javascript_include_tag :application
    = csrf_meta_tags
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1.0'}
    %title Eat & Drive - Portal
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{'type' => 'button', 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Eat&Drive Portal', root_path, :class => 'brand'
          .nav-collapse.collapse
            %ul.nav.pull-right
              %li.navbar-text Logged in as
              %li.dropdown
                %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                  = @current_user.name
                  - if @current_user.staff?
                    %span.label.label-inverse staff
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'My account', profile_path
                  %li.divider
                  %li= link_to 'Log out', logout_path, :confirm => 'Are you sure you want to log out?', :method => :delete
            %ul.nav
              %li= link_to 'Dashboard', root_path
              %li.dropdown
                %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                  My Eat&Drive
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'My favorites', root_path
                  %li= link_to 'My orders', root_path
                  %li= link_to 'My payment methods', root_path
              - if @current_user.staff?
                %li.dropdown
                  %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                    Store
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to 'Opening hours', root_path
                    %li= link_to 'Products', root_path
                    %li= link_to 'Order history', root_path
                    %li= link_to 'Campaigns', campaigns_path
              - if @current_user.superuser?
                %li.dropdown
                  %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                    Administration
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to 'Organizations', organizations_path
                    %li= link_to 'Users', users_path
    .container
      .row
        .span12
          = yield
      %hr
      %footer
        %p &copy; Eat&amp;Drive 2013